# This is a basic workflow to help you get started with Actions

name: NN -cve delta upload to Storage

on:
  schedule:
    - cron: '0 */8 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      id-token: write
    
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
    
      - name: Get JSON Files
        shell: pwsh
        run: |
          $localpath = "./"
          $pathurl = "${{secrets.LOCAL_DELTA}}?${{secrets.AZURE_STORAGE_SAS_TOKEN}}"
          
          echo $pathurl
          
          #get last delta timestamp from azure storage
          $lastfetch = Invoke-RestMethod -uri $pathurl  | select -First 1 |%{$_.fetchTime}
          
          # get the deltalog
          $deltalog = 'https://raw.githubusercontent.com/CVEProject/cvelistV5/main/cves/deltaLog.json'
          
          $alldata = Invoke-RestMethod -Uri $deltalog
          $uploadlist = $alldata | Where-Object {$_.fetchtime -GT $lastfetch} |select new | %{$_.new | %{$_.githubLink}}
          $uploadlist += $alldata | Where-Object {$_.fetchtime -GT $lastfetch} |select updated  | %{$_.updated | %{$_.githubLink}}
          
          # parse the index of items in the delta log with a timestamp greater than or equal to the delta fetchtime.
          foreach ($link in $uploadlist) {
              #save it locally, swapping out the path. 
              $downloaded = Invoke-RestMethod -Uri $link | ConvertTo-Json -Depth 100
              
              new-item -force -path  $($link.Replace( ${{ secrets.TRUNCATE_PATH }}, $localpath)) -value $downloaded -type file
          }

      - name: save the delta 
        shell: pwsh
        run: |
           $delta = 'https://raw.githubusercontent.com/CVEProject/cvelistV5/main/cves/delta.json'
           $localpath = "./"
           #get the current delta
           $deltafile = Invoke-RestMethod -Uri $delta
           #now, save the delta ...
           new-item -force -path  $($delta.Replace( ${{ secrets.TRUNCATE_PATH }}, $localpath)) -value $deltafile -type file
      
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --auth-mode key \
              --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
              --source "./cves" \
              --destination "${{ secrets.CONTAINER }}" \
              --destination-path "/cves" \
              --overwrite true                  
      
      - name: logout
        run: |
              az logout
        if: always() 
