# This is a basic workflow to help you get started with Actions
name: Update Fork Every 4 Hours

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */8 * * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0	
        with:	
            ssh-private-key: ${{ secrets.CVEPRIVATEKEY }}
      - name: get current commit timestamp
        run: |
           echo "LASTCOMMIT1=$(git show --no-patch --no-notes --pretty='%cI' --date=format:'%Y-%m-%d'T'%H:%M'Z')" >> "$GITHUB_ENV" 
           echo "LASTCOMMIT2=${{github.event.head_commit.timestamp}}" >> "$GITHUB_ENV" 
      - name: show current commit timestamp
        run: |
           echo GIT SHOW TIMESTAMP   : ${{env.LASTCOMMIT1}}
           echo HEAD_COMMIT TIMESTAMP: ${{env.LASTCOMMIT2}}

      - name: Configure Git
        run: |
          git config --global user.email "raulr+github@live.com"
          git config --global user.name "ElJefeDSecurIT"
      - name: Add and fetch upstream remote
        run: |
           git remote add upstream https://github.com/CVEProject/cvelistV5/
           git fetch upstream 
      - name: Merge upstream changes
        run: git merge upstream/main  --strategy-option theirs --allow-unrelated-histories
      - name: push origin Main
        run: git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --auth-mode key \
              --account-name "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
              --source "./cves" \
              --destination "${{ secrets.CONTAINER }}" \
              --destination-path "/cves"\
              --if-unmodified-since ${{env.LASTCOMMIT1}}
                         
      - name: logout
        run: |
              az logout
        if: always() 
  
