# This is a basic workflow to help you get started with Actions
name: NN- Update branch 8pm fridays

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 20 * * 5'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0	
        with:	
            ssh-private-key: ${{ secrets.CVEPRIVATEKEY }}
      - name: get current commit timestamp
        run: |
           echo "LASTCOMMIT1=$(git show --no-patch --no-notes --pretty=%cd --date=format:%Y-%m-%d'T'%H:%M'Z')" >> "$GITHUB_ENV" 
      - name: show current commit timestamp
        run: |
           echo GIT SHOW TIMESTAMP   : ${{env.LASTCOMMIT1}}           
      - name: Configure Git
        run: |
          git config --global user.email "raulr+github@live.com"
          git config --global user.name "ElJefeDSecurIT"
      - name: Add and fetch upstream remote
        run: |
           git remote add upstream https://github.com/CVEProject/cvelistV5/
           git fetch upstream 
      - name: Merge upstream changes
        run: git merge upstream/main  --strategy-option theirs --allow-unrelated-histories
      - name: push origin Main
        run: git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}                 

  
